mkdir: cannot create directory ‘resultsdump/job_taus40d200_18297940’: File exists
mkdir: cannot create directory ‘resultsdump/job_taus40d200_18297940/pickles’: File exists
mkdir: cannot create directory ‘resultsdump/job_taus40d200_18297940/errors’: File exists
2024-02-02 18:39:49.728088: W external/tsl/tsl/framework/bfc_allocator.cc:296] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.39GiB with freed_by_count=0. The caller indicates that this is not a failure, but this may mean that there could be performance gains if more memory were available.
Traceback (most recent call last):
  File "/n/holyscratch01/pehlevan_lab/Lab/mletey/ICLexperiments/experiment/remote/largerruns/tau.py", line 35, in <module>
    state, hist = train(config, data_iter=iter(linobject), batch_size=np.min([1000,P]), loss='mse', test_every=1000, train_iters=500000, optim=optax.adamw,lr=1e-4)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/holyscratch01/pehlevan_lab/Lab/mletey/ICLexperiments/experiment/remote/largerruns/../../../trainmini.py", line 168, in train
    state = create_train_state(init_rng, model, samp_x, optim=optim, **opt_kwargs) # the samp_x data is not used during this initialisation
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/holyscratch01/pehlevan_lab/Lab/mletey/ICLexperiments/experiment/remote/largerruns/../../../trainmini.py", line 47, in create_train_state
    params = model.init(rng, dummy_input)['params']
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/holyscratch01/pehlevan_lab/Lab/mletey/ICLexperiments/experiment/remote/largerruns/../../../model/transformer.py", line 240, in __call__
    y = TransformerBlock(
        ^^^^^^^^^^^^^^^^^
  File "/n/holyscratch01/pehlevan_lab/Lab/mletey/ICLexperiments/experiment/remote/largerruns/../../../model/transformer.py", line 180, in __call__
    x = SingleHeadSelfAttention(self.config)(inputs, decoder_mask, idxs=idxs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/holyscratch01/pehlevan_lab/Lab/mletey/ICLexperiments/experiment/remote/largerruns/../../../model/transformer.py", line 104, in __call__
    query = dense(name='query')(inputs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/home05/mletey/.conda/envs/try4/lib/python3.12/site-packages/flax/linen/linear.py", line 280, in __call__
    y = dot_general(
        ^^^^^^^^^^^^
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 3637897216 bytes.
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
